version: 2
updates:
  # Example configuration for npm dependencies
  # This section will only be relevant if you add a package.json file in the future.
  - package-ecosystem: "npm"
    directory: "/" # Location of the dependencies (root of the repository)
    schedule:
      interval: "weekly" # Update frequency
    target-branch: "main" # Target branch for updates
    commit-message:
      prefix: "chore" # Commit message prefix
    open-pull-requests-limit: 5 # Maximum number of open PRs at a time
    reviewers:
      - "Betrand1999" # Reviewer username
    assignees:
      - "Betrand1999" # Assignee username
    ignore:
      - dependency-name: "*" # Ignore all dependencies for now, adjust when dependencies are added

  # Example configuration for Python dependencies
  # This section is only relevant if you plan to use Python with a requirements.txt or similar.
  - package-ecosystem: "pip"
    directory: "/" # Location of the dependencies
    schedule:
      interval: "daily" # Update frequency
    target-branch: "main" # Target branch for updates
    commit-message:
      prefix: "update" # Commit message prefix
    open-pull-requests-limit: 3 # Maximum number of open PRs at a time
    reviewers:
      - "Betrand1999" # Reviewer username
    assignees:
      - "Betrand1999" # Assignee username
    ignore:
      - dependency-name: "*" # Ignore all dependencies for now, adjust when dependencies are added
