version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
    reviewers:
      - "Betrand1999"
    assignees:
      - "Betrand1999"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "update"
    open-pull-requests-limit: 3
    reviewers:
      - "Betrand1999"
    assignees:
      - "Betrand1999"
