name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # This specifies the runner; you can use ubuntu-latest or your self-hosted label.
    container:
      image: betrand1997/myapp:latest # Your custom Docker image from Docker Hub or your private registry

    steps:
      - uses: actions/checkout@v4
      - name: Build the site in the jekyll/builder container
        run: |
          chmod -R 777 /srv/jekyll
          jekyll build --future
